Ack, testall_wstiny seems to be failing nondeterministically.  For example, it passed on revision 3600 1/6 times.  Perhaps that was when I ran it manually vs. it being run by the nighttime script?  Or vice versa?
When it fails, it gets this error:

  /home/newton/3603_WS_test_copy_1224669601/src/demos/wavescope/query.c:57: undefined reference to 
`cuttype10_theitem_fld1_fld1_get'

Ah, ok, mig is failing because of being unable to run msp430-gcc.
It's a PATH problem.

Committing small changes to fix testall_wstiny 

I explicitely mess with the path from that script.